In [1]:
from google.colab import drive
drive.mount("/content/drive")

!pip3 install kaggle
!cp /content/drive/'My Drive'/ML/kaggle_binary /usr/local/bin/kaggle
!mkdir /root/.kaggle
!cp /content/drive/'My Drive'/ML/kaggle.json /root/.kaggle/
!chmod 600 /root/.kaggle/kaggle.json

#drive.flush_and_unmount()

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [2]:
!kaggle competitions download digit-recognizer
!unzip digit-recognizer.zip
!rm digit-recognizer.zip

 59% 9.00M/15.3M [00:00<00:00, 35.4MB/s]
100% 15.3M/15.3M [00:00<00:00, 55.8MB/s]
Archive:  digit-recognizer.zip
  inflating: train.csv               
  inflating: test.csv                
  inflating: sample_submission.csv   


In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style('whitegrid')

%matplotlib inline

In [0]:
dataset = pd.read_csv("train.csv")

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42000 entries, 0 to 41999
Columns: 785 entries, label to pixel783
dtypes: int64(785)
memory usage: 251.5 MB


In [6]:
dataset.describe()

label   pixel0   pixel1  ...  pixel781  pixel782  pixel783
count  42000.000000  42000.0  42000.0  ...   42000.0   42000.0   42000.0
mean       4.456643      0.0      0.0  ...       0.0       0.0       0.0
std        2.887730      0.0      0.0  ...       0.0       0.0       0.0
min        0.000000      0.0      0.0  ...       0.0       0.0       0.0
25%        2.000000      0.0      0.0  ...       0.0       0.0       0.0
50%        4.000000      0.0      0.0  ...       0.0       0.0       0.0
75%        7.000000      0.0      0.0  ...       0.0       0.0       0.0
max        9.000000      0.0      0.0  ...       0.0       0.0       0.0

[8 rows x 785 columns]

In [7]:
dataset.nunique().count()

785

In [8]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Flatten
from keras.layers.convolutional import Convolution2D
from keras.layers.convolutional import MaxPooling2D
from sklearn.preprocessing import LabelBinarizer

Using TensorFlow backend.


In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(dataset.iloc[:, 1:].values, dataset.iloc[:, 0].values, test_size=0.2, random_state=42)

In [0]:
X_train = X_train.reshape(X_train.shape[0],28,28,1).astype('float32')
X_train = X_train/255.0                          
                                  #try another model with standard scaler
X_test = X_test.reshape(X_test.shape[0],28,28,1).astype('float32')
X_test = X_test/255.0
#y_train = dataset.values[:,0]

In [11]:
X_train

array([[[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
 

In [12]:
y_train

array([6, 5, 3, ..., 2, 6, 0])

In [0]:
lb = LabelBinarizer()
y_train = lb.fit_transform(y_train)
y_test = lb.transform(y_test)

In [14]:
y_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [15]:
model = Sequential()
model.add(Convolution2D(32, 5, 5, border_mode='valid', input_shape=(28, 28, 1), activation = 'relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Convolution2D(16, 3, 3, activation = 'relu'))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(output_dim = 128, activation = 'relu'))
model.add(Dense(output_dim = 70, activation = 'relu'))
model.add(Dense(output_dim = 10, activation = 'softmax'))

model.compile(loss = "categorical_crossentropy", optimizer = 'adam', metrics=['accuracy'])






Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.




/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (5, 5), input_shape=(28, 28, 1..., activation="relu", padding="valid")`
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(16, (3, 3), activation="relu")`
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=128)`
  import sys
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=70)`
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", units=10)`
  if __name__ == '__main__':


In [16]:
model.fit(X_train, y_train, epochs=50, batch_size=64)
                                      #without image augmentation


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Epoch 1/50





33600/33600 [==============================] - 11s 321us/step - loss: 0.2471 - acc: 0.9249
Epoch 2/50
33600/33600 [==============================] - 3s 103us/step - loss: 0.0712 - acc: 0.9776
Epoch 3/50
33600/33600 [==============================] - 4s 110us/step - loss: 0.0487 - acc: 0.9848
Epoch 4/50
33600/33600 [==============================] - 3s 102us/step - loss: 0.0405 - acc: 0.9868
Epoch 5/50
33600/33600 [==============================] - 3s 98us/step - loss: 0.0330 - acc: 0.9897
Epoch 6/50
33600/33600 [==============================] - 4s 107us/step - loss: 0.0261 - acc: 0.9919
Epoch 7/50
33600/33600 [==============================] - 4s 107us/step - loss: 0.0253 - acc: 0.9915
Epoch 8/50
33600/33600 [==============================] - 3s 102us/step - loss: 0.0194 - acc: 0.9939
Epoch 9/50
33600/33600 [==============================] - 4s 106us/step - loss: 0.0177 - a

In [17]:
model.evaluate(X_test, y_test, batch_size=64)

8400/8400 [==============================] - 0s 44us/step


[0.05988354564969865, 0.9902380952380953]

In [0]:
test_dataset = pd.read_csv('test.csv')

In [19]:
test_dataset.describe()

pixel0   pixel1   pixel2  ...  pixel781  pixel782  pixel783
count  28000.0  28000.0  28000.0  ...   28000.0   28000.0   28000.0
mean       0.0      0.0      0.0  ...       0.0       0.0       0.0
std        0.0      0.0      0.0  ...       0.0       0.0       0.0
min        0.0      0.0      0.0  ...       0.0       0.0       0.0
25%        0.0      0.0      0.0  ...       0.0       0.0       0.0
50%        0.0      0.0      0.0  ...       0.0       0.0       0.0
75%        0.0      0.0      0.0  ...       0.0       0.0       0.0
max        0.0      0.0      0.0  ...       0.0       0.0       0.0

[8 rows x 784 columns]

In [0]:
X = test_dataset.values
X = X.reshape(X.shape[0],28,28,1).astype('float32')
X = X/255.0

In [0]:
predictions = model.predict(X)

In [22]:
predictions

array([[1.3636129e-17, 9.4607094e-21, 1.0000000e+00, ..., 2.2921137e-17,
        6.0177493e-20, 2.5782182e-21],
       [1.0000000e+00, 1.0971109e-18, 1.9854748e-18, ..., 2.4417579e-17,
        4.1110718e-17, 1.9748780e-17],
       [6.3049033e-15, 2.1492919e-19, 2.4618598e-15, ..., 3.2499865e-13,
        1.2305099e-10, 1.0000000e+00],
       ...,
       [7.1564989e-31, 2.6700599e-16, 6.5235890e-20, ..., 1.7531881e-22,
        1.6566742e-19, 3.0987771e-16],
       [8.1846202e-15, 1.3479995e-16, 1.2171793e-13, ..., 2.1553510e-12,
        3.2767155e-12, 1.0000000e+00],
       [2.8444483e-13, 1.5453887e-16, 1.0000000e+00, ..., 1.5367106e-14,
        3.0431236e-15, 1.0069471e-16]], dtype=float32)

In [23]:
lb.classes_

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
result = predictions.argmax(axis=1)

In [25]:
result.shape

(28000,)

In [0]:
pred = pd.DataFrame({'Label':result})

In [0]:
pred.index.name = "ImageId"

In [28]:
pred.index += 1
pred

Label
ImageId       
1            2
2            0
3            9
4            9
5            3
...        ...
27996        9
27997        7
27998        3
27999        9
28000        2

[28000 rows x 1 columns]

In [0]:
pred.to_csv("digit_submission.csv", index=True)
!mv digit_submission.csv drive/'My Drive'/ML/kaggle/

In [0]:
drive.flush_and_unmount()